{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2 as cv\n",
    "import mysql.connector\n",
    "import datetime\n",
    "import face_recognition as fr\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Initialise Camera\n",
    "vid = cv.VideoCapture(0)\n",
    "dt=datetime.date.today()\n",
    "\n",
    "# connecting to the db\n",
    "mydb=mysql.connector.connect(\n",
    "    host=\"localhost\",\n",
    "    user=\"root\",\n",
    "    passwd=\"\",\n",
    "    database=\"cisco_thingqbator\"\n",
    "    )\n",
    "db_cursor=mydb.cursor()\n",
    "\n",
    "#Create a cascade classifier object\n",
    "face_cascade = cv.CascadeClassifier(\"Open CV/haarcascade_frontalface_default.xml\")\n",
    "faces=[]\n",
    "\n",
    "#No. of frames\n",
    "nof = 0\n",
    "\n",
    "#List to store each face, to be done later\n",
    "face_list=[]\n",
    "\n",
    "folder = \"Desktop/Projects-Astha/imgs\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "while True:\n",
    "    #checks if the day hasn't changed or if the month has changed\n",
    "    now=datetime.date.today()\n",
    "    if dt.day+1==now.day or dt.day>now.day:\n",
    "       \n",
    "        count = len(face_list)\n",
    "\n",
    "        today=datetime.date.today()\n",
    "        #sql_query = \"INSERT INTO primary_daywise VALUES(dt, count)\"\n",
    "        db_cursor.execute(\"INSERT INTO primary_daywise(Date, Count) VALUES(%s,%s)\",(today, count))\n",
    "        mydb.commit()\n",
    "        print(db_cursor.rowcount, \"Record Inserted\")\n",
    "        #Empty face list on a new day\n",
    "        face_list=[]\n",
    "       \n",
    "\n",
    "\n",
    "    #check returns bool, frame returns the image as numpy array\n",
    "    check, frame = vid.read()\n",
    "    if not check:\n",
    "        continue\n",
    " \n",
    "   \n",
    "   \n",
    "    #Convert image to grayscale\n",
    "    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)\n",
    "   \n",
    "    #Detect multiple faces. Returns a list of faces in the current frame.\n",
    "    faces = face_cascade.detectMultiScale(gray, 1.5, 5)\n",
    "   \n",
    "    #If frame has no face detected, continue loop.\n",
    "    if len(faces)==0:\n",
    "        continue\n",
    "   \n",
    "    #Increment number of frames\n",
    "    nof += 1\n",
    "       \n",
    "    #Draw a rectangle around each face\n",
    "    for top, left, bottom, right in faces:\n",
    "        gray = cv.rectangle(gray, (top, left), (top+bottom, left+right), (0,255,0), 1)\n",
    "       \n",
    "   \n",
    "    #Process only if faces is not empty\n",
    "    if len(faces)!=0:\n",
    "        for face in faces[:1]:\n",
    "            x, y, w, h = face\n",
    "           \n",
    "            # Get the face ROI(region of interest)\n",
    "            offset = 7\n",
    "            face_section = gray[y-offset:y+h+offset, x-offset:x+w+offset]\n",
    "            face_section = cv.resize(face_section, (100, 100))\n",
    "           \n",
    "            #Write current face to local folder as jpg image\n",
    "            cv.imwrite(os.path.join(folder,\"frame{:d}.jpg\".format(nof)), face_section)\n",
    "           \n",
    "            #Load the face as jpg image\n",
    "            image = fr.load_image_file( \"Desktop/imgs/frame{:d}.jpg\".format(nof))\n",
    "           \n",
    "            #Convert image into encoding\n",
    "            if len(fr.face_encodings(image))!=0:\n",
    "                face_encoding = fr.face_encodings(image)[0]\n",
    "               \n",
    "                #If face_list is empty or current face is unique, append its encoding\n",
    "                if len(face_list)==0 or compare(face_list, face_encoding, nof) == False:\n",
    "                    face_list.append(face_encoding)\n",
    "                    print(\"appended\")\n",
    "                     \n",
    "               \n",
    "               \n",
    "    #Show the faces with rectangle drawn on them\n",
    "    cv.imshow(\"Face\", face_section)\n",
    "   \n",
    "    #Wait for 1ms per frame. Quit if 'q' pressed.\n",
    "    key = cv.waitKey(1)\n",
    "    if key == ord('q'):\n",
    "        break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Print no. of frames\n",
    "print(\"No. of frames:\", nof)\n",
    "\n",
    "#Print no. of unique faces\n",
    "print(\"No. of faces:\", len(face_list))\n",
    "\n",
    "\n",
    "\n",
    "vid.release()\n",
    "cv.destroyAllWindows()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
